# DigitalOcean App Platform Configuration
# This file defines how your app will be deployed on DigitalOcean

name: grokisanaughtypuppy
region: nyc

# Backend API Service
services:
  - name: backend
    # Source configuration
    github:
      repo: Phazzie/grokisanaughtypuppy
      branch: main
      deploy_on_push: true
    
    # Build configuration
    source_dir: /backend
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: XAI_API_KEY
        value: ${XAI_API_KEY}  # Set this in DigitalOcean dashboard
        type: SECRET
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}  # Auto-populated from database component
        type: SECRET
    
    # Health check
    health_check:
      http_path: /api/health
    
    # Resources
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month
    
    # HTTP configuration
    http_port: 8080
    
    # Routes
    routes:
      - path: /api

# Frontend Static Site
static_sites:
  - name: frontend
    github:
      repo: Phazzie/grokisanaughtypuppy
      branch: main
      deploy_on_push: true
    
    source_dir: /grok-chat
    
    # Build command
    build_command: npm install && npm run build -- --configuration production
    
    # Output directory
    output_dir: dist/grok-chat/browser
    
    # Environment variables for build
    envs:
      - key: API_URL
        value: ${backend.PUBLIC_URL}/api
    
    # Routes - catchall for Angular routing
    routes:
      - path: /
    
    # Error document for SPA routing
    error_document: index.html

# Optional: PostgreSQL Database
# Uncomment to add a managed database
databases:
  - name: db
    engine: PG  # PostgreSQL
    version: "15"
    production: false  # Set to true for production (starts at $15/month)

# Optional: Redis for caching/sessions
# Uncomment if needed
# databases:
#   - name: redis
#     engine: REDIS
#     version: "7"
#     production: false
