#!/bin/bash
# Quick setup script for Gemini API (FREE)

echo "🚀 Gemini API Setup for CI/CD"
echo "=============================="
echo ""
echo "Step 1: Get your FREE Gemini API key"
echo "  👉 Visit: https://makersuite.google.com/app/apikey"
echo "  👉 Sign in with Google account"
echo "  👉 Click 'Create API key'"
echo "  👉 Copy the key (starts with AIzaSy...)"
echo ""
echo "Step 2: Add to GitHub"
echo "  👉 Go to: https://github.com/$(git config --get remote.origin.url | sed 's/.*github.com[:\/]\(.*\)\.git/\1/')/settings/secrets/actions"
echo "  👉 Click 'New repository secret'"
echo "  👉 Name: GEMINI_API_KEY"
echo "  👉 Value: [paste your key]"
echo "  👉 Click 'Add secret'"
echo ""
echo "Step 3: Test it locally (optional)"
echo "  👉 export GEMINI_API_KEY='your-key-here'"
echo "  👉 ./scripts/ci/gemini-helper.sh configure"
echo "  👉 ./scripts/ci/gemini-helper.sh review src/app/app.ts"
echo ""
echo "Step 4: Trigger a workflow"
echo "  👉 gh workflow run ai-code-review.yml"
echo "  👉 Or create a PR and it runs automatically!"
echo ""
echo "✅ That's it! AI-powered CI/CD for FREE!"
echo ""
echo "📊 Gemini Free Tier:"
echo "  - 15 requests per minute"
echo "  - 1,500 requests per day"
echo "  - Perfect for most projects!"
echo ""
echo "💡 Pro Tip:"
echo "  Keep using Claude Code (this CLI) for interactive development"
echo "  Use Gemini API for automated CI/CD tasks"
echo ""
